services:
  - type: web
    name: personal-finance-dashboard-server
    env: node
    buildCommand: cd server && pnpm install && pnpm run build
    startCommand: cd server && pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
